# Generated by Django 5.0.6 on 2025-05-26 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ADMINISTRADOR',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ESPECIALIDAD',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_med', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('est_med', models.IntegerField()),
                ('especialidad', models.ForeignKey(db_column='ESPECIALIDAD_id_especialidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicos.especialidad')),
            ],
            options={
                'db_table': 'MEDICO',
            },
        ),
        migrations.CreateModel(
            name='ObservacionesMedico',
            fields=[
                ('id_observ', models.IntegerField(primary_key=True, serialize=False)),
                ('medico', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('medico_fk', models.ForeignKey(db_column='MEDICO_id_med', on_delete=django.db.models.deletion.CASCADE, to='medicos.medico')),
            ],
            options={
                'db_table': 'OBSERVACIONES_MEDICO',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=350)),
                ('medico', models.ForeignKey(db_column='MEDICO_id_med', on_delete=django.db.models.deletion.CASCADE, to='medicos.medico')),
            ],
            options={
                'db_table': 'PERMISOS',
            },
        ),
    ]
